# Generated by Django 3.1.7 on 2022-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_customer_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_status',
            field=models.CharField(choices=[('Accept', 'Accept'), ('Reject', 'Reject')], max_length=50, null=True),
        ),
    ]
