# Generated by Django 3.1.7 on 2022-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0005_leavereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='leave_feedback',
            field=models.TextField(default=None),
        ),
    ]
