# Generated by Django 3.1.7 on 2022-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0008_auto_20220208_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereport',
            name='leave_feedback',
            field=models.TextField(default='0'),
        ),
    ]
