# Generated by Django 3.1.7 on 2022-02-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0013_auto_20220208_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereport',
            name='leave_feedback',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
