# Generated by Django 3.1.7 on 2022-02-08 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0014_auto_20220208_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereport',
            name='leave_feedback',
        ),
    ]
