# Generated by Django 3.1.7 on 2022-02-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0019_remove_leavereport_leave_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_feedback', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='leavereport',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.userfeedback'),
        ),
    ]
