# Generated by Django 3.1.7 on 2022-02-08 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0020_auto_20220208_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavereport',
            name='feedback',
        ),
    ]
