# Generated by Django 3.1.7 on 2022-02-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0021_remove_leavereport_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereport',
            name='leave_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
