# Generated by Django 3.1.7 on 2022-02-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0022_auto_20220211_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereport',
            name='leave_feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.userfeedback'),
        ),
    ]
