# Generated by Django 3.1.7 on 2022-03-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0024_auto_20220215_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apponitment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='apponitment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='apponitment',
            name='status',
        ),
        migrations.DeleteModel(
            name='userFeedback',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_status',
        ),
        migrations.DeleteModel(
            name='Apponitment',
        ),
        migrations.DeleteModel(
            name='reservationStatus',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
